/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;


/**
 * <p>Java class for APoCPath complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="APoCPath">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}path"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}searchStrings" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)

public class APoCPath{
	
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String path;
    
    protected SearchStrings searchStrings;
    protected String accessRightID;

    /**
     * APoCPath constructor
     */
    public APoCPath() {
        super();
    }

    /**
     * APoCPath constructor
     * @param path - The path of the APoCPath
     */
    public APoCPath(String path) {
        super();
        this.path = path;
    }

    /**
     * Gets the value of the path property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the property accessRightID.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */

    public String getAccessRightID() {
        return accessRightID;
    }

    /**
     * Sets the value of the property accessRightID.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */

    public void setAccessRightID(String value) {
        this.accessRightID = value;
    }

    /**
     * Gets the value of the searchStrings property.
     *
     * @return possible object is {@link SearchStrings }
     *
     */
    public SearchStrings getSearchStrings() {
        if(searchStrings==null){
            return new SearchStrings();
        }
        return searchStrings;
    }

    /**
     * Sets the value of the searchStrings property.
     *
     * @param value
     *            allowed object is {@link SearchStrings }
     *
     */
    public void setSearchStrings(SearchStrings value) {
        this.searchStrings = value;
    }

    public String toString() {
        return "APoCPath [path=" + path + ", accessRightID=" + accessRightID
                + ", searchStrings=" + searchStrings + "]";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((accessRightID == null) ? 0 : accessRightID.hashCode());
		result = prime * result + ((path == null) ? 0 : path.hashCode());
		result = prime * result
				+ ((searchStrings == null) ? 0 : searchStrings.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		APoCPath other = (APoCPath) obj;
		if (accessRightID == null) {
			if (other.accessRightID != null) {
				return false;
			}
		} else if (!accessRightID.equals(other.accessRightID)) {
			return false;
		}
		if (path == null) {
			if (other.path != null) {
				return false;
			}
		} else if (!path.equals(other.path)) {
			return false;
		}
		if (searchStrings == null) {
			if (other.searchStrings != null) {
				return false;
			}
		} else if (!searchStrings.equals(other.searchStrings)) {
			return false;
		}
		return true;
	}
    
}
