/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//

package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;

/**
 * <p>
 * Java class for Applications complex type.
 *
 * <p>
 * Applications resource is a collection of {@link Application} resources which
 * are registered to the hosting SCL represented by the {@link SclBase}
 * resource.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Applications">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}applicationCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}applicationAnncCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}mgmtObjsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
public class Applications extends Resource {

	@XmlSchemaType(name = "dateTime")
	protected String creationTime;
	@XmlSchemaType(name = "dateTime")
	protected String lastModifiedTime;

	protected NamedReferenceCollection applicationCollection;

	protected NamedReferenceCollection applicationAnncCollection;
	@XmlSchemaType(name = "anyURI")
	protected String subscriptionsReference;
	@XmlSchemaType(name = "anyURI")
	protected String mgmtObjsReference;

	/**
	 * Gets the value of the creationTime property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCreationTime() {
		return creationTime;
	}

	/**
	 * Sets the value of the creationTime property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setCreationTime(String value) {
		this.creationTime = value;
	}

	/**
	 * Gets the value of the lastModifiedTime property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLastModifiedTime() {
		return lastModifiedTime;
	}

	/**
	 * Sets the value of the lastModifiedTime property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLastModifiedTime(String value) {
		this.lastModifiedTime = value;
	}

	/**
	 * Gets the value of the applicationCollection property.
	 *
	 * @return possible object is {@link NamedReferenceCollection }
	 *
	 */
	public NamedReferenceCollection getApplicationCollection() {
		if (applicationCollection == null) {
			applicationCollection = new NamedReferenceCollection();
		}
		return applicationCollection;
	}

	/**
	 * Sets the value of the applicationCollection property.
	 *
	 * @param value
	 *            allowed object is {@link NamedReferenceCollection }
	 *
	 */
	public void setApplicationCollection(NamedReferenceCollection value) {
		this.applicationCollection = value;
	}

	/**
	 * Gets the value of the applicationAnncCollection property.
	 *
	 * @return possible object is {@link NamedReferenceCollection }
	 *
	 */
	public NamedReferenceCollection getApplicationAnncCollection() {
		if (applicationAnncCollection == null) {
			applicationAnncCollection = new NamedReferenceCollection();
		}
		return applicationAnncCollection;

	}

	/**
	 * Sets the value of the applicationAnncCollection property.
	 *
	 * @param value
	 *            allowed object is {@link NamedReferenceCollection }
	 *
	 */
	public void setApplicationAnncCollection(NamedReferenceCollection value) {
		this.applicationAnncCollection = value;
	}

	/**
	 * Gets the value of the subscriptionsReference property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSubscriptionsReference() {
		if (subscriptionsReference == null && uri != null) {
			return uri+Refs.SUBSCRIPTIONS_REF;
		} else {
			return subscriptionsReference;
		}
	}

	/**
	 * Sets the value of the subscriptionsReference property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSubscriptionsReference(String value) {
		this.subscriptionsReference = value;
	}

	/**
	 * Gets the value of the mgmtObjsReference property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getMgmtObjsReference() {
		if (mgmtObjsReference == null && uri != null) {
			return uri+Refs.MGMTOBJS_REF;				
		} else {
			return mgmtObjsReference;
		}
	}

	/**
	 * Sets the value of the mgmtObjsReference property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setMgmtObjsReference(String value) {
		this.mgmtObjsReference = value;
	}

	public String toString() {
		return "Applications [accessRightID=" + accessRightID
				+ ", creationTime=" + creationTime + ", lastModifiedTime="
				+ lastModifiedTime + ", applicationCollection="
				+ applicationCollection + ", applicationAnncCollection="
				+ applicationAnncCollection + ", subscriptionsReference="
				+ subscriptionsReference + ", mgmtObjsReference="
				+ mgmtObjsReference + ", uri=" + uri + "]";
	}

	/**
	 * Copy all changes to the current object
	 * 
	 * @param resource
	 */
	public void copyOf(Applications resource) {
		this.accessRightID = resource.accessRightID;
		this.lastModifiedTime = resource.lastModifiedTime;
		this.searchStrings = resource.searchStrings;
	}
}
