/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//

package org.eclipse.om2m.commons.resource;

import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.DatatypeConfigurationException;



/**
 * <p>Classe Java class for ConnectionParamSet complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ConnectionParamSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}securityConnectionId"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}securityKmcIndex"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}securityLifetime"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}securityM2MKey"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}sclId"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}securitymIdFlags"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectionParamSet", propOrder = {
        "securityConnectionId",
        "securityKmcIndex",
        "securityLifetime",
        "securityM2MKey",
        "sclId",
        "securitymIdFlags"
})

@XmlRootElement
public class ConnectionParamSet {

    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger securityConnectionId;
    @XmlSchemaType(name = "unsignedInt")
    protected long securityKmcIndex;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected String securityLifetime;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] securityM2MKey;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String sclId;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] securitymIdFlags;

    /**
     * Gets the value of the securityConnectionId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     * @throws NoSuchAlgorithmException
     *
     */
    public BigInteger getSecurityConnectionId() throws NoSuchAlgorithmException {

        return securityConnectionId;
    }

    /**
     * Sets the value of the securityConnectionId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setSecurityConnectionId(BigInteger value) {
        this.securityConnectionId = value;
    }

    /**
     * Gets the value of the securityKmcIndex property.
     * @throws NoSuchAlgorithmException
     *
     */
    public long getSecurityKmcIndex() throws NoSuchAlgorithmException {

        return securityKmcIndex;
    }

    /**
     * Sets the value of the securityKmcIndex property.
     *
     */
    public void setSecurityKmcIndex(long value) {
        this.securityKmcIndex = value;
    }

    /**
     * Gets the value of the securityLifetime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     * @throws DatatypeConfigurationException
     *
     */
    public String getSecurityLifetime() throws DatatypeConfigurationException {

        return securityLifetime;
    }

    /**
     * Sets the value of the securityLifetime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSecurityLifetime(String value) {
        this.securityLifetime = value;
    }

    /**
     * Gets the value of the securityM2MKey property.
     *
     * @return
     *     possible object is
     *     {@link String }
     * @throws NoSuchAlgorithmException
     *
     */
    public byte[] getSecurityM2MKey() throws NoSuchAlgorithmException {

        return securityM2MKey;
    }

    /**
     * Sets the value of the securityM2MKey property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSecurityM2MKey(byte[] value) {
        if(value == null) {
            this.securityM2MKey = new byte[0];
        } else {
            this.securityM2MKey = Arrays.copyOf(value, value.length);
        }
    }

    /**
     * Gets the value of the sclId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSclId() {
        return sclId;
    }

    /**
     * Sets the value of the sclId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSclId(String value) {
        this.sclId = value;
    }

    /**
     * Gets the value of the securitymIdFlags property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public byte[] getSecuritymIdFlags() {

        return securitymIdFlags;
    }

    /**
     * Sets the value of the securitymIdFlags property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSecuritymIdFlags(byte[] value) {
        if(value == null) {
            this.securitymIdFlags = new byte[0];
        } else {
            this.securitymIdFlags = Arrays.copyOf(value, value.length);
        }
    }

    public String toString() {
        return "ConnectionParamSet [securityConnectionId="
                + securityConnectionId + ", securityKmcIndex="
                + securityKmcIndex + ", securityLifetime=" + securityLifetime
                + ", securityM2MKey=" + Arrays.toString(securityM2MKey)
                + ", sclId=" + sclId + ", securitymIdFlags="
                + Arrays.toString(securitymIdFlags) + "]";
    }

}
