/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;



/**
 * <p>Java class for Containers complex type.
 *
 * <p>Containers resource is a collection of {@link Container}, {@link ContainerAnnc},
 * {@link LocationContainer} or {@link LocationContainerAnnc} resources.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Containers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}containerCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}containerAnncCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}locationContainerCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}locationContainerAnncCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
public class Containers extends Resource {

	@Override
	public String toString() {
		return "Containers [accessRightID=" + accessRightID + ", creationTime="
				+ creationTime + ", lastModifiedTime=" + lastModifiedTime
				+ ", containerCollection=" + containerCollection
				+ ", containerAnncCollection=" + containerAnncCollection
				+ ", locationContainerCollection="
				+ locationContainerCollection
				+ ", locationContainerAnncCollection="
				+ locationContainerAnncCollection + ", subscriptionsReference="
				+ subscriptionsReference + "]";
	}


	@XmlSchemaType(name = "dateTime")
	protected String creationTime;
	@XmlSchemaType(name = "dateTime")
	protected String lastModifiedTime;
	protected NamedReferenceCollection containerCollection;
	protected NamedReferenceCollection containerAnncCollection;
	protected NamedReferenceCollection locationContainerCollection;
	protected NamedReferenceCollection locationContainerAnncCollection;
	@XmlSchemaType(name = "anyURI")
	protected String subscriptionsReference;

	/**
	 * Gets the value of the creationTime property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getCreationTime() {
		return creationTime;
	}

	/**
	 * Sets the value of the creationTime property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setCreationTime(String value) {
		this.creationTime = value;
	}

	/**
	 * Gets the value of the lastModifiedTime property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getLastModifiedTime() {
		return lastModifiedTime;
	}

	/**
	 * Sets the value of the lastModifiedTime property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setLastModifiedTime(String value) {
		this.lastModifiedTime = value;
	}

	/**
	 * Gets the value of the containerCollection property.
	 *
	 * @return
	 *     possible object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public NamedReferenceCollection getContainerCollection() {
		if (containerCollection == null){
			containerCollection = new NamedReferenceCollection();
		}
		return containerCollection;
	}

	/**
	 * Sets the value of the containerCollection property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public void setContainerCollection(NamedReferenceCollection value) {
		this.containerCollection = value;
	}

	/**
	 * Gets the value of the containerAnncCollection property.
	 *
	 * @return
	 *     possible object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public NamedReferenceCollection getContainerAnncCollection() {
		if (containerAnncCollection == null){
			containerAnncCollection = new NamedReferenceCollection();
		}
		return containerAnncCollection;
	}

	/**
	 * Sets the value of the containerAnncCollection property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public void setContainerAnncCollection(NamedReferenceCollection value) {
		this.containerAnncCollection = value;
	}

	/**
	 * Gets the value of the locationContainerCollection property.
	 *
	 * @return
	 *     possible object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public NamedReferenceCollection getLocationContainerCollection() {
		if (locationContainerCollection == null){
			locationContainerCollection = new NamedReferenceCollection();
		}
		return locationContainerCollection;
	}

	/**
	 * Sets the value of the locationContainerCollection property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public void setLocationContainerCollection(NamedReferenceCollection value) {
		this.locationContainerCollection = value;
	}

	/**
	 * Gets the value of the locationContainerAnncCollection property.
	 *
	 * @return
	 *     possible object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public NamedReferenceCollection getLocationContainerAnncCollection() {
		if (locationContainerAnncCollection == null){
			locationContainerAnncCollection = new NamedReferenceCollection();
		}
		return locationContainerAnncCollection;
	}

	/**
	 * Sets the value of the locationContainerAnncCollection property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link NamedReferenceCollection }
	 *
	 */
	public void setLocationContainerAnncCollection(NamedReferenceCollection value) {
		this.locationContainerAnncCollection = value;
	}

	/**
	 * Gets the value of the subscriptionsReference property.
	 *
	 * @return
	 *     possible object is
	 *     {@link String }
	 *
	 */
	public String getSubscriptionsReference() {
		if (subscriptionsReference == null && uri != null) {
			return uri+Refs.SUBSCRIPTIONS_REF;
		} else {
			return subscriptionsReference;
		}
	}

	/**
	 * Sets the value of the subscriptionsReference property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *
	 */
	public void setSubscriptionsReference(String value) {
		this.subscriptionsReference = value;
	}
}
