/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//

package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;



/**
 * <p>Java class for ContentInstances complex type.
 *
 * <p>ContentInstances resource represents the collection of content instances in a container.
 * It shall also keep a track of the latest (newest) and the oldest instance.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ContentInstances">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}currentNrOfInstances" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}currentByteSize" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}contentInstanceCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}latest" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}oldest" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement

public class ContentInstances extends Resource {

    @XmlSchemaType(name = "dateTime")
    protected String creationTime;
    @XmlSchemaType(name = "dateTime")
    protected String lastModifiedTime;
    protected Long currentNrOfInstances;
    protected Long currentByteSize;
    
    protected ContentInstanceCollection contentInstanceCollection;
    
    protected ReferenceToNamedResource latest;
    
    protected ReferenceToNamedResource oldest;
    @XmlSchemaType(name = "anyURI")
    
    protected String subscriptionsReference;

    /**
     * Gets the value of the creationTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastModifiedTime(String value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the currentNrOfInstances property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getCurrentNrOfInstances() {
        return currentNrOfInstances;
    }

    /**
     * Sets the value of the currentNrOfInstances property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setCurrentNrOfInstances(Long value) {
        this.currentNrOfInstances = value;
    }

    /**
     * Gets the value of the currentByteSize property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getCurrentByteSize() {
        return currentByteSize;
    }

    /**
     * Sets the value of the currentByteSize property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setCurrentByteSize(Long value) {
        this.currentByteSize = value;
    }

    /**
     * Gets the value of the contentInstanceCollection property.
     *
     * @return
     *     possible object is
     *     {@link ContentInstanceCollection }
     *
     */
    public ContentInstanceCollection getContentInstanceCollection() {
        if (contentInstanceCollection == null){
            contentInstanceCollection = new ContentInstanceCollection();
        }
        return contentInstanceCollection;
    }

    /**
     * Sets the value of the contentInstanceCollection property.
     *
     * @param value
     *     allowed object is
     *     {@link ContentInstanceCollection }
     *
     */
    public void setContentInstanceCollection(ContentInstanceCollection value) {
        this.contentInstanceCollection = value;
    }

    /**
     * Gets the value of the latest property.
     *
     * @return
     *     possible object is
     *     {@link ReferenceToNamedResource }
     *
     */
    public ReferenceToNamedResource getLatest() {
        return latest;
    }

    /**
     * Sets the value of the latest property.
     *
     * @param value
     *     allowed object is
     *     {@link ReferenceToNamedResource }
     *
     */
    public void setLatest(ReferenceToNamedResource value) {
        this.latest = value;
    }

    /**
     * Gets the value of the oldest property.
     *
     * @return
     *     possible object is
     *     {@link ReferenceToNamedResource }
     *
     */
    public ReferenceToNamedResource getOldest() {
        return oldest;
    }

    /**
     * Sets the value of the oldest property.
     *
     * @param value
     *     allowed object is
     *     {@link ReferenceToNamedResource }
     *
     */
    public void setOldest(ReferenceToNamedResource value) {
        this.oldest = value;
    }

    /**
     * Gets the value of the subscriptionsReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubscriptionsReference() {
    	if (subscriptionsReference == null && uri != null) {
    		return uri+Refs.SUBSCRIPTIONS_REF;
    	} else {
			return subscriptionsReference;
    	}
    }

    /**
     * Sets the value of the subscriptionsReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

    public String toString() {
        return "ContentInstances [creationTime=" + creationTime
                + ", lastModifiedTime=" + lastModifiedTime
                + ", currentNrOfInstances=" + currentNrOfInstances
                + ", currentByteSize=" + currentByteSize
                + ", contentInstanceCollection=" + contentInstanceCollection
                + ", latest=" + latest + ", oldest=" + oldest
                + ", subscriptionsReference=" + subscriptionsReference + "]";
    }
}
