/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;



/**
 * <p>Java class for Group complex type.
 *
 * <p>Group resource is used to define and access groups of other resources.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}expirationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}searchStrings" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}announceTo" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}memberType" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}currentNrOfMembers" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}maxNrOfMembers" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}members" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}membersContentReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://uri.etsi.org/m2m}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
public class Group extends Resource {

    @XmlSchemaType(name = "dateTime")
    protected String expirationTime;
    @XmlSchemaType(name = "dateTime")
    protected String creationTime;
    @XmlSchemaType(name = "dateTime")
    protected String lastModifiedTime;

    protected AnnounceTo announceTo;

    protected MemberType memberType;
    protected Long currentNrOfMembers;
    protected Long maxNrOfMembers;

    protected AnyURIList members;
    @XmlSchemaType(name = "anyURI")

    protected String membersContentReference;
    @XmlSchemaType(name = "anyURI")

    protected String subscriptionsReference;
    @XmlAttribute(name = "id", namespace = "http://uri.etsi.org/m2m")
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the expirationTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExpirationTime(String value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the creationTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastModifiedTime(String value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the announceTo property.
     *
     * @return
     *     possible object is
     *     {@link AnnounceTo }
     *
     */
    public AnnounceTo getAnnounceTo() {
        return announceTo;
    }

    /**
     * Sets the value of the announceTo property.
     *
     * @param value
     *     allowed object is
     *     {@link AnnounceTo }
     *
     */
    public void setAnnounceTo(AnnounceTo value) {
        this.announceTo = value;
    }

    /**
     * Gets the value of the memberType property.
     *
     * @return
     *     possible object is
     *     {@link MemberType }
     *
     */
    public MemberType getMemberType() {
        return memberType;
    }

    /**
     * Sets the value of the memberType property.
     *
     * @param value
     *     allowed object is
     *     {@link MemberType }
     *
     */
    public void setMemberType(MemberType value) {
        this.memberType = value;
    }

    /**
     * Gets the value of the currentNrOfMembers property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getCurrentNrOfMembers() {
        return currentNrOfMembers;
    }

    /**
     * Sets the value of the currentNrOfMembers property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setCurrentNrOfMembers(Long value) {
        this.currentNrOfMembers = value;
    }

    /**
     * Gets the value of the maxNrOfMembers property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getMaxNrOfMembers() {
        return maxNrOfMembers;
    }

    /**
     * Sets the value of the maxNrOfMembers property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setMaxNrOfMembers(Long value) {
        this.maxNrOfMembers = value;
    }

    /**
     * Gets the value of the members property.
     *
     * @return
     *     possible object is
     *     {@link AnyURIList }
     *
     */
    public AnyURIList getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     *
     * @param value
     *     allowed object is
     *     {@link AnyURIList }
     *
     */
    public void setMembers(AnyURIList value) {
        this.members = value;
    }

    /**
     * Gets the value of the membersContentReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMembersContentReference() {
    	if (membersContentReference == null && uri != null) {
    		return uri+Refs.MEMBERSCONTENT_REF;
    	} else {
			return membersContentReference;
    	}
    }

    /**
     * Sets the value of the membersContentReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMembersContentReference(String value) {
        this.membersContentReference = value;
    }

    /**
     * Gets the value of the subscriptionsReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubscriptionsReference() {
    	if (subscriptionsReference == null && uri != null) {
    		return uri+Refs.SUBSCRIPTIONS_REF;
    	} else {
			return subscriptionsReference;
    	}
    }

    /**
     * Sets the value of the subscriptionsReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

}
