/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.24 at 02:41:37 AM CEST
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;



/**
 * <p>Java Class for MgmtObjs complex type.
 *
 * <p>MgmtObjs resource represents a collection of {@link MgmtObj} resources and {@link MgmtCmd} resources.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MgmtObjs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}mgmtObjCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}mgmtCmdCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
public class MgmtObjs extends Resource {

    @XmlSchemaType(name = "dateTime")
    protected String creationTime;
    @XmlSchemaType(name = "dateTime")
    protected String lastModifiedTime;
    protected NamedReferenceCollection mgmtObjCollection;
    protected NamedReferenceCollection mgmtCmdCollection;
    @XmlSchemaType(name = "anyURI")
    protected String subscriptionsReference;

    /**
     * Gets the value of the property creationTime.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the property creationTime.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the property lastModifiedTime.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the property lastModifiedTime.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastModifiedTime(String value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the property mgmtObjCollection.
     *
     * @return
     *     possible object is
     *     {@link NamedReferenceCollection }
     *
     */
    public NamedReferenceCollection getMgmtObjCollection() {
        if (mgmtObjCollection == null){
            mgmtObjCollection = new NamedReferenceCollection();
        }
        return mgmtObjCollection;
    }

    /**
     * Sets the value of the property mgmtObjCollection.
     *
     * @param value
     *     allowed object is
     *     {@link NamedReferenceCollection }
     *
     */
    public void setMgmtObjCollection(NamedReferenceCollection value) {
        this.mgmtObjCollection = value;
    }

    /**
     * Gets the value of the property mgmtCmdCollection.
     *
     * @return
     *     possible object is
     *     {@link NamedReferenceCollection }
     *
     */
    public NamedReferenceCollection getMgmtCmdCollection() {
        if (mgmtCmdCollection == null){
            mgmtCmdCollection = new NamedReferenceCollection();
        }
        return mgmtCmdCollection;
    }

    /**
     * Sets the value of the property mgmtCmdCollection.
     *
     * @param value
     *     allowed object is
     *     {@link NamedReferenceCollection }
     *
     */
    public void setMgmtCmdCollection(NamedReferenceCollection value) {
        this.mgmtCmdCollection = value;
    }

    /**
     * Gets the value of the property subscriptionsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubscriptionsReference() {
    	if (subscriptionsReference == null && uri != null) {
    		return uri+Refs.SUBSCRIPTIONS_REF;
    	} else {
			return subscriptionsReference;
    	}
    }

    /**
     * Sets the value of the property subscriptionsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

}
