/*******************************************************************************
 * Copyright (c) 2013-2015 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Thierry Monteil (Project co-founder) - Management and initial specification,
 *         conception and documentation.
 *     Mahdi Ben Alaya (Project co-founder) - Management and initial specification,
 *         conception, implementation, test and documentation.
 *     Christophe Chassot - Management and initial specification.
 *     Khalil Drira - Management and initial specification.
 *     Yassine Banouar - Initial specification, conception, implementation, test
 *         and documentation.
 *     Guillaume Garzone - Conception, implementation, test and documentation.
 *     Francois Aissaoui - Conception, implementation, test and documentation.
 ******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.24 at 02:52:11 AM CEST
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;



/**
 * <p>Java Class for SclBase complex type.
 *
 * <p>SclBase resource contains all other resources of the hosting SCL.
 * An SclBase is the root of all other resources it contains.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SclBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}searchStrings" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}aPocHandling" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}sclsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}applicationsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}containersReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}groupsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}discoveryReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)

public class SclBase extends Resource {

    @XmlSchemaType(name = "dateTime")
    protected String creationTime;
    @XmlSchemaType(name = "dateTime")
    protected String lastModifiedTime;
    protected APocHandling aPocHandling;
    @XmlSchemaType(name = "anyURI")
     
    protected String sclsReference;
    @XmlSchemaType(name = "anyURI")
     
    protected String applicationsReference;
    @XmlSchemaType(name = "anyURI")
     
    protected String containersReference;
    @XmlSchemaType(name = "anyURI")
     
    protected String groupsReference;
    @XmlSchemaType(name = "anyURI")
     
    protected String accessRightsReference;
    @XmlSchemaType(name = "anyURI")
     
    protected String subscriptionsReference;
    @XmlSchemaType(name = "anyURI")
     
    protected String discoveryReference;

    public SclBase() {
        super();
    }

    /**
     * Gets the value of the property creationTime.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */

    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the property creationTime.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */

    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the property lastModifiedTime.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */

    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the property lastModifiedTime.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */

    public void setLastModifiedTime(String value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the property aPocHandling.
     *
     * @return
     *     possible object is
     *     {@link APocHandling }
     *
     */
    public APocHandling getAPocHandling() {
        return aPocHandling;
    }

    /**
     * Sets the value of the property aPocHandling.
     *
     * @param value
     *     allowed object is
     *     {@link APocHandling }
     *
     */
    public void setAPocHandling(APocHandling value) {
        this.aPocHandling = value;
    }

    /**
     * Gets the value of the property sclsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSclsReference() {
    	if (sclsReference == null && uri != null) { 
    		return uri + Refs.SCLS_REF;
    	} else {
    		return sclsReference;
    	}
    }

    /**
     * Sets the value of the property sclsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSclsReference(String value) {
        this.sclsReference = value;
    }

    /**
     * Gets the value of the property applicationsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getApplicationsReference() {
    	if (applicationsReference == null && uri != null) {
    		return uri+Refs.APPLICATIONS_REF;
    	} else {
			return applicationsReference;
    	}
    }

    /**
     * Sets the value of the property applicationsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setApplicationsReference(String value) {
        this.applicationsReference = value;
    }

    /**
     * Gets the value of the property containersReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContainersReference() {
    	if (containersReference == null && uri != null) {
    		return uri+Refs.CONTAINERS_REF;
    	} else {
			return containersReference;
    	}
    }

    /**
     * Sets the value of the property containersReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContainersReference(String value) {
        this.containersReference = value;
    }

    /**
     * Gets the value of the property groupsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGroupsReference() {
    	if (groupsReference == null && uri != null) {
    		return uri+Refs.GROUPS_REF;
    	} else {
			return groupsReference;
    	}
    }

    /**
     * Sets the value of the property groupsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGroupsReference(String value) {
        this.groupsReference = value;
    }

    /**
     * Gets the value of the property accessRightsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccessRightsReference() {
    	if (accessRightsReference == null && uri != null) {
    		return uri+Refs.ACCESSRIGHTS_REF;
    	} else {
			return accessRightsReference;
    	}
    }

    /**
     * Sets the value of the property accessRightsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccessRightsReference(String value) {
        this.accessRightsReference = value;
    }

    /**
     * Gets the value of the property subscriptionsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubscriptionsReference() {
    	if (subscriptionsReference == null && uri != null) {
    		return uri+Refs.SUBSCRIPTIONS_REF;
    	} else {
			return subscriptionsReference;
    	}
    }

    /**
     * Sets the value of the property subscriptionsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

    /**
     * Gets the value of the property discoveryReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDiscoveryReference() {
    	if (discoveryReference == null && uri != null) {
    		return uri+Refs.DISCOVERY_REF;
    	} else {
			return discoveryReference;
    	}
    }

    /**
     * Sets the value of the property discoveryReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDiscoveryReference(String value) {
        this.discoveryReference = value;
    }

    @Override
    public String toString() {
        return "SclBase [accessRightID=" + accessRightID + ", searchStrings="
                + searchStrings + ", creationTime=" + creationTime
                + ", lastModifiedTime=" + lastModifiedTime + ", aPocHandling="
                + aPocHandling + ", sclsReference=" + sclsReference
                + ", applicationsReference=" + applicationsReference
                + ", containersReference=" + containersReference
                + ", groupsReference=" + groupsReference
                + ", accessRightsReference=" + accessRightsReference
                + ", subscriptionsReference=" + subscriptionsReference
                + ", discoveryReference=" + discoveryReference + ", uri=" + uri
                + "]";
    }
    
}
